### ISSUE TITLE
Running update script without internet deletes Node-Red

### ISSUE THREAD

**Issue by slevey087** [node-red/raspbian-deb-package#4]
I tried to run the update-nodejs-and-nodered script, but I didn't realize that I didn't have internet at the time. The result was that the script deleted node-red, and apparently also deleted itself! 

I'm sure I'll be able to figure out how to reinstall it, but, thought you might like to know.

**Comment by slevey087** [comment]
I was able to get it back by copying and pasting the contents of update-nodejs-and-nodered from Github to the file in usr/bin/, which had become a blank text file. Ran it, it worked, it all seems to be fine thus far.

**Comment by dceejay** [comment]
Ouch. Thanks for finding this out the hard way. And good recovery.

**Comment by slevey087** [comment]
Thanks. Good luck with the fix!

**Comment by dceejay** [comment]
Hi i have added a new version to the comments on #3 - If you are brave / have a backup of your SD - then please try it (both not-connected and connected) to internet. Thanks
