### ISSUE TITLE
Upgrade script should upgrade itself first

### ISSUE THREAD

**Issue by jheiselman** [node-red/raspbian-deb-package#5]
When running the upgrade script, the last thing it does is upgrade itself.

The problem with this is that if I want to upgrade, say to go from Node 6.x to Node 8.x, running the upgrade script the first time will just reinstall my entire Node/NPM platform as is (Node-Red may get upgraded) since the version of Node is hard coded into the script. Then, the upgrade script will get upgraded to a version that will install Node 8.x and I'd have to run the entire process again.

It would be beneficial to either have the upgrade script check somewhere first which version of Node to upgrade to, or have it upgrade itself, then re-launch to ensure that it is upgrading to the latest supported version.

**Comment by dceejay** [comment]
Hi, yes - older versions of the script did that. The latest versions of the script replace the one on the pi with this version 
https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-pi
which does exactly that. Of course until the installed one has been upgraded once it won't be like that...
